### ISSUE TITLE
Problem with cropping @2x images

### ISSUE THREAD

**Issue by jonasskafte** [tomaszsita/wp-manual-image-crop#38]
— Repost from the [Wordpress support page](https://wordpress.org/support/topic/problem-with-cropping-2x-images?replies=2) —

Hi there,

Firstly, thanks for providing such a great plugin to the WP community!

I'm currently experiencing problems with cropping @2x images and I can't work out what the issue is. Here's an example where you can clearly see the difference:

[Standard image](http://lilykamper.com/wp-content/uploads/2014/10/20150205_LILYKAMPER_2015_0075-359x359.jpg)
[@2x image](http://lilykamper.com/wp-content/uploads/2014/10/20150205_LILYKAMPER_2015_0075-359x359@2x.jpg)

I've tried to crop the image both with the 'Generate Retina/HiDPI (@2x)' field ticked as well as without it ticked, but that didn't help (by the way I liked it more when this field was ticked by default, but that might just be me). I've also completely purged all caches. Besides using Manual Image Crop I also use WP Retina 2x, which hasn't been a problem in the past.

I hope for your help.

All the best,

Jonas

**Comment by jonasskafte** [comment]
Hi again,

Sorry to be a bother, but I just want to follow up on this issue as I really hope that it can be fixed somehow (as earlier mentioned, I would have contributed with a fix myself, had I only been good enough to code it). It seems that there's a bunch of people experiencing similar issues since the last update.

If there's no plan to look into this, then please let me know and I'll look into using a different plugin.

That said, I really appreciate the efforts that has already been made to build this, otherwise, great plugin! :-)

Thanks,

Jonas

PS. Is it perhaps somehow possible to download an older version of the plugin?

**Comment by odie2** [comment]
Hi,

Someone already fixed it 26 days ago in #40.
Author have very long delays between updates.

For PS - https://pl.wordpress.org/plugins/manual-image-crop/developers/ here you are ;)

Greetings

**Comment by jonasskafte** [comment]
Thanks for letting me know odie2!! :-)

I wish I'd noticed earlier though, but this is great news!

I've told the other guys over on Wordpress: https://wordpress.org/support/topic/problem-with-cropping-2x-images?replies=7#post-7617157

I hope the author will merge the two versions soon and update the plug-in more regularly – as I really appreciate what it does and the work that has already been put into this.

Cheers!
